huggingface/course

chapters/es/_toctree.yml
chapters/es/chapter1/1.mdx
chapters/es/chapter1/10.mdx
chapters/es/chapter1/2.mdx
chapters/es/chapter1/3.mdx
chapters/es/chapter1/4.mdx
chapters/es/chapter1/5.mdx
chapters/es/chapter1/6.mdx
chapters/es/chapter1/7.mdx
chapters/es/chapter1/8.mdx
chapters/es/chapter1/9.mdx

Hi! 👋🏻
Here are the files for Chapter 1 translated into spanish, with the corresponding `_toctree.yml` file, related to issue #38.
I didn't translate the embedded images and code snippets as I'm not sure if that's the desired action.
Additionally, in some instances I translated a word but kept the original in english - usually in parenthesis - when I felt it would be useful to have the original term.
Hope this helps!

Chapter 1 translated to spanish

---

.github/workflows/build_documentation.yml
.github/workflows/build_pr_documentation.yml
chapters/he/_toctree.yml
chapters/he/chapter0/1.mdx

Created _toctree.yml file and chapter0 translated to Hebrew
Issue #48 :
0 - Setup : 1.mdx

Chapter0 translation to Hebrew

---

chapters/fr/_toctree.yml
chapters/fr/chapter5/1.mdx
chapters/fr/chapter5/2.mdx
chapters/fr/chapter5/3.mdx
chapters/fr/chapter5/4.mdx
chapters/fr/chapter5/5.mdx
chapters/fr/chapter5/6.mdx
chapters/fr/chapter5/7.mdx
chapters/fr/chapter5/8.mdx

Here is the translation of the chapter 5 into fr
Linked to #44

French Translation - Chapter 5

---

chapters/ja/_toctree.yml
chapters/ja/chapter1/1.mdx

In this PR, I translate chapter1/1.mdx.

Translate to Japanese Chapter1/1

---

chapters/tr/_toctree.yml
chapters/tr/chapter1/1.mdx
chapters/tr/chapter1/5.mdx

I think the translations are done, sorry for the late pr about chapter 1.1
Also I saw that nobody take responsibility about 1.5, I finished it, too 💥#41 
I think there are some configurations for rendering in the website, YAML config, etc. But I don't know how to do it. So it needs review @lewtun 😣

[TR] Translated Chapter 1.1 and 1.5 🤗

---

chapters/en/chapter7/7.mdx

Fix QA pipeline link

---

chapters/pt/_toctree.yml
chapters/pt/chapter4/1.mdx
chapters/pt/chapter4/2.mdx

[PT] add chapter 4.1 and 4.2

---

chapters/es/_toctree.yml
chapters/es/chapter3/1.mdx
chapters/es/chapter3/2.mdx

Related to https://github.com/huggingface/course/issues/38

Spanish Chapter 3: sections 1 & 2

---

chapters/en/_toctree.yml
chapters/fr/_toctree.yml

cc @lbourdois this also fixes the `fr` build :)

Fix Gradio ToC

---

chapters/pt/_toctree.yml
chapters/pt/chapter4/4.mdx
chapters/pt/chapter4/5.mdx

[PT] add chapter 4.4 and 4.5

---

chapters/tr/_toctree.yml
chapters/tr/chapter3/1.mdx

[TR] Chapter 3/1

---

chapters/fa/_toctree.yml

Remove comments from Persian ToC

---

chapters/en/chapter6/3b.mdx

Reported on the forums: https://discuss.huggingface.co/t/fast-tokenizers-in-the-qa-pipeline-tensorflow-numpy-error/18374

Add missing numpy import

---

chapters/es/_toctree.yml
chapters/es/chapter8/1.mdx
chapters/es/chapter8/2.mdx

Hi, 
from Chapter 8, here is 8.1 and 8.2 files translated into Spanish, related to issue #38 
I followed the French translate manner for some parts and the suggestions from the Translating file and Glossary (#192). 
I hope this will be useful!

[ES] translate sections 8.1 and 8.2

---

chapters/en/chapter9/2.mdx
chapters/en/chapter9/3.mdx
chapters/en/chapter9/4.mdx
chapters/en/chapter9/5.mdx
chapters/en/chapter9/6.mdx
chapters/en/chapter9/7.mdx
utils/code_formatter.py
utils/generate_notebooks.py

This PR:
* Refactors the logic in `generate_notebooks.py` to account for the new way we handle chapter/section names in `_toctree.yml`
* Adds Colab and StudioLab links to the Gradio chapters
* Fixes some small things in the code formatting

Fix notebook generation

---

chapters/pt/_toctree.yml
chapters/pt/chapter5/4.mdx

[PT] add  5.4

---

chapters/fr/chapter9/2.mdx
chapters/fr/chapter9/3.mdx
chapters/fr/chapter9/4.mdx
chapters/fr/chapter9/5.mdx
chapters/fr/chapter9/6.mdx
chapters/fr/chapter9/7.mdx

Add Gradio nbs links to fr

---

chapters/pt/_toctree.yml
chapters/pt/chapter5/5.mdx

[PT] add 5.5

---

chapters/es/_toctree.yml
chapters/es/chapter3/4.mdx
chapters/es/glossary/1.mdx

Add Spanish chapter3/section4, update TOC and Glossary

---

chapters/pt/_toctree.yml
chapters/pt/chapter5/6.mdx
chapters/pt/chapter5/7.mdx

[PT] add 5.6 and 5.7

---

chapters/en/chapter7/5.mdx
chapters/en/chapter9/3.mdx
chapters/en/chapter9/9.mdx
chapters/fr/chapter9/8.mdx

Hi,
Some visual corrections for chapters 7 and 9 in English, and for French, the update of chapter 9/8 to be up to date with PR #237

[EN] Visual corrections

---

chapters/pt/_toctree.yml
chapters/pt/event/1.mdx

[PT] add event 1

---

chapters/pt/_toctree.yml
chapters/pt/chapter8/1.mdx
chapters/pt/chapter8/2.mdx

[PT] add chapter  8.1 and 8.2

---

chapters/pt/_toctree.yml
chapters/pt/chapter1/3.mdx

3.mdx of chapter 01

---

chapters/it/_toctree.yml
chapters/it/chapter2/1.mdx
chapters/it/chapter2/2.mdx

I have translated the first two sections of Chapter 2 into Italian.

Italian translation Ch 2/1, 2/2

---

README.md
chapters/fr/chapter9/4.mdx
utils/generate_notebooks.py

This PR extends the `generate_notebooks.py` script to export the MDX files as Jupyter notebooks for any language.
I've done a diff check on the English notebooks to ensure nothing is broken with these changes.
Related to https://github.com/huggingface/course/issues/309

Enable notebooks to be generated in any language

---

README.md
utils/generate_notebooks.py

This PR refactors the notebooks generation script to create the notebooks for all languages

Generate notebooks for all languages

---

chapters/en/chapter7/3.mdx
chapters/fr/chapter7/3.mdx
chapters/ja/chapter7/3.mdx
chapters/vi/chapter7/3.mdx
chapters/zh-CN/chapter7/3.mdx

Fix whole word masking labels

---

chapters/de/_toctree.yml
chapters/de/chapter4/1.mdx
chapters/de/chapter4/2.mdx
chapters/de/chapter4/3.mdx
chapters/de/glossary/1.mdx

So I am finally done with this one.
I'd great if a native speaker like @MarcusFra or @JesperDramsch could take a look at it, just to stay on the safe side and catch silly mistakes I might have done :)

Translation Chapter 4

---

chapters/en/chapter7/2.mdx
chapters/fr/chapter7/2.mdx
chapters/ja/chapter7/2.mdx
chapters/vi/chapter7/2.mdx
chapters/zh-CN/chapter7/2.mdx

Fixes a small consistency issue reported on the forums: https://discuss.huggingface.co/t/chapter-7-questions/11746/46?u=lewtun

Fix id2label types

---

chapters/es/_toctree.yml
chapters/es/chapter2/6.mdx

Translate file `chapter2/6.mdx` to spanish
Related to: #38

i18n: ES - translate file chapter2/6.mdx

---

chapters/ru/chapter3/4.mdx

The line above already translated the English sentence to Russian.

Remove translated string

---

chapters/en/chapter3/3.mdx

This is very minor, but the blue 'n' [on this page](https://huggingface.co/course/chapter3/3?fw=pt) was eating away at my soul :)

Add Python syntax highlighting

---

chapters/fr/_toctree.yml
chapters/fr/chapter1/1.mdx
chapters/fr/chapter1/3.mdx
chapters/fr/chapter7/2.mdx
chapters/fr/chapter7/3.mdx
chapters/fr/chapter7/4.mdx
chapters/fr/chapter7/5.mdx
chapters/fr/chapter7/6.mdx
chapters/fr/chapter7/7.mdx
chapters/fr/glossary/1.mdx

Hi @lewtun 
This PR adds to the French version :
- the FAQ
- the glossary
- Matt's modifications on TF code
We must be pretty good for the French version now :)

[FR] Add FAQ and more

---

chapters/en/chapter8/4.mdx
chapters/fr/chapter8/4.mdx
chapters/it/chapter8/4.mdx
chapters/vi/chapter8/4.mdx
chapters/zh-CN/chapter8/4.mdx

Reported on the forums here: https://discuss.huggingface.co/t/chapter-8-questions/11747/2?u=lewtun

Fix notebook link

---

README.md

Hey there 👋 ,
I just added to the documentation that preview does work with windows.
Also modified the documentation of doc-builder: https://github.com/huggingface/doc-builder/pull/332

Update documentation to mention that preview does not work with windows

---

chapters/en/chapter1/1.mdx

Two small typos fixed in the first chapter.

Fixes small typos

---

.github/workflows/quality.yml
subtitles/zh-CN/57_what-is-perplexity.srt

docs(zh-cn): Reviewed 57_what-is-perplexity.srt #390

docs(zh-cn): Reviewed 57_what-is-perplexity.srt

---

subtitles/zh-CN/59_data-processing-for-translation.srt

timestamp: 00:02:15,960 --> 00:02:18,560
modification:
(indistinct) --> Keras
notes:
I re-watched the video on YouTube, and listened for times on this point, it sounds like Keras for the most. Further confirmation is needed.

docs(zh-cn): Reviewed 59_data-processing-for-translation.srt

---

subtitles/zh-CN/60_what-is-the-bleu-metric.srt

docs(zh-cn): Reviewed 60_what-is-the-bleu-metric.srt #390

docs(zh-cn): Reviewed 60_what-is-the-bleu-metric.srt

---

subtitles/zh-CN/55_data-processing-for-token-classification.srt

docs(zh-cn): Reviewed 55_data-processing-for-token-classification.srt #390

docs(zh-cn): Reviewed 55_data-processing-for-token-classification.srt

---

subtitles/zh-CN/62_what-is-the-rouge-metric.srt

docs(zh-cn): Reviewed 62_what-is-the-rouge-metric.srt #390 
Fixed several content error in original english subtitle
timestamp: 00:00:18,180 --> 00:00:21,180
modification:
tech --> text
timestamp: 00:02:34,290 --> 00:02:36,870
modification:
abstracter --> abstractive
timestamp: 00:03:21,660 --> 00:03:23,910
modification:
load metric --> load_metric

docs(zh-cn): Reviewed 62_what-is-the-rouge-metric.srt

---

subtitles/en/62_what-is-the-rouge-metric.srt

Fixed several content error in original english subtitle
timestamp: 00:00:18,180 --> 00:00:21,180
modification:
tech --> text
timestamp: 00:02:34,290 --> 00:02:36,870
modification:
abstracter --> abstractive
timestamp: 00:03:21,660 --> 00:03:23,910
modification:
load metric --> load_metric

fixed errors in english subtitle of ep.62

---

subtitles/zh-CN/65_data-processing-for-question-answering.srt

docs(zh-cn): Reviewed 65_data-processing-for-question-answering.srt #390

docs(zh-cn): Reviewed 65_data-processing-for-question-answering.srt

---

subtitles/README.md
subtitles/en/00_welcome-to-the-hugging-face-course.srt
subtitles/fr/00_welcome-to-the-hugging-face-course.srt
subtitles/fr/03_what-is-transfer-learning.srt
subtitles/fr/68_data-collators-a-tour.srt
subtitles/zh-CN/00_welcome-to-the-hugging-face-course.srt
utils/convert_bilingual_monolingual.py
utils/generate_subtitles.py
utils/validate_translation.py

cc @lbourdois all the French subtitles have now been uploaded to YouTube 🥳 !

Fix French subtitles + refactor conversion script

---

subtitles/zh-CN/67_the-post-processing-step-in-question-answering-(tensorflow).srt

docs(zh-cn): Reviewed 67_the-post-processing-step-in-question-answering-(tensorflow).srt #390

docs(zh-cn): Reviewed 67_the-post-processing-step-in-question-answering-(tensorflow).srt

---

subtitles/zh-CN/66_the-post-processing-step-in-question-answering-(pytorch).srt

docs(zh-cn): Reviewed 66_the-post-processing-step-in-question-answering-(pytorch).srt #390

docs(zh-cn): Reviewed 66_the-post-processing-step-in-question-answering-(pytorch).srt

---

subtitles/zh-CN/01_the-pipeline-function.srt

docs(zh-cn): Reviewed 01_the-pipeline-function.srt

---

subtitles/zh-CN/02_the-carbon-footprint-of-transformers.srt

docs(zh-cn): Reviewed 02_the-carbon-footprint-of-transformers.srt

---

chapters/en/chapter5/5.mdx
chapters/es/chapter5/5.mdx
chapters/fr/chapter5/5.mdx
chapters/it/chapter5/5.mdx
chapters/pt/chapter5/5.mdx
chapters/vi/chapter5/5.mdx
chapters/zh-CN/chapter5/5.mdx

Fixing chapter 5 reference links that were previously broken.

Fix chapter 5 links

---

subtitles/fr/63_data-processing-for-causal-language-modeling.srt
subtitles/fr/tasks_00_🤗-tasks-token-classification.srt
subtitles/fr/tasks_01_🤗-tasks-question-answering.srt
subtitles/fr/tasks_02_🤗-tasks-causal-language-modeling.srt
subtitles/fr/tasks_03_🤗-tasks-masked-language-modeling.srt
subtitles/fr/tasks_04_🤗-tasks-summarization.srt
subtitles/fr/tasks_05_🤗-tasks-translation.srt
subtitles/fr/titles-and-descriptions.txt

Hi @lewtun,
In this PR:
- additions of the transcripts of 🤗 Tasks videos (+ titles and descriptions)
- fix subtitles/fr/63_data-processing-for-causal-language-modeling.srt (https://www.youtube.com/watch?v=ma1TrR7gE7I) where transcripts on YouTube should be replaced but especially the title of the video and the description

[FR] Add 🤗  Tasks videos

---

subtitles/zh-CN/68_data-collators-a-tour.srt

docs(zh-cn): Reviewed 68_data-collators-a-tour.srt #390

docs(zh-cn): Reviewed 68_data-collators-a-tour.srt

---

subtitles/zh-CN/03_what-is-transfer-learning.srt

docs(zh-cn): Reviewed 03_what-is-transfer-learning.srt

---

subtitles/zh-CN/32_managing-a-repo-on-the-model-hub.srt

docs(zh-cn): 32_managing-a-repo-on-the-model-hub.srt #390 
modifie subtitle
ts: 00:03:21,300 --> 00:03:24,050
change: idea --> id

docs(zh-cn): 32_managing-a-repo-on-the-model-hub.srt

---

subtitles/zh-CN/33_the-push-to-hub-api-(pytorch).srt

docs(zh-cn): 33_the-push-to-hub-api-(pytorch).srt #390 
Subtitles from  00:04:13,380 to 00:04:22,923 are not consistent with the YouTube Video(https://www.youtube.com/watch?v=Zh0FfmVrKX0), further comfirmation is needed.

docs(zh-cn): 33_the-push-to-hub-api-(pytorch).srt

---

subtitles/zh-CN/07_transformer-models-encoder-decoders.srt

docs(zh-cn): Reviewed 07_transformer-models-encoder-decoders.srt

---

subtitles/zh-CN/24_the-trainer-api.srt

docs(zh-cn)： Reviewed No.24  - The Trainer API

---

subtitles/zh-CN/06_transformer-models-decoders.srt

docs(zh-cn): Reviewed 06_transformer-models-decoders.srt

---

subtitles/zh-CN/05_transformer-models-encoders.srt

docs(zh-cn): Reviewed 05_transformer-models-encoders.srt

---

subtitles/en/33_the-push-to-hub-api-(pytorch).srt

timestamp: 00:00:26,640 --> 00:00:28,620
modification: notification --> authentication
timestamp: 00:04:21,113 --> 00:04:22,923
modification: of --> or

fixed subtitle errors in ep.33 (Enligsh Version)

---

chapters/zh-CN/_toctree.yml
chapters/zh-CN/chapter4/2.mdx

docs(zh-cn)： Reviewed Chapter 4/2

---

chapters/zh-CN/chapter7/1.mdx

docs(zh-cn): Reviewed Chapter 7/1

---

subtitles/zh-CN/41_text-embeddings-&-semantic-search.srt

docs(zh-cn): Reviewed 41_text-embeddings-&-semantic-search.srt #390

docs(zh-cn): Reviewed 41_text-embeddings-&-semantic-search.srt

---

subtitles/zh-CN/40_uploading-a-dataset-to-the-hub.srt

docs(zh-cn): Reviewed 40_uploading-a-dataset-to-the-hub.srt #390

docs(zh-cn): Reviewed 40_uploading-a-dataset-to-the-hub.srt

---

subtitles/zh-CN/39_memory-mapping-&-streaming.srt

docs(zh-cn): Reviewed 39_memory-mapping-&-streaming.srt #390

docs(zh-cn): Reviewed 39_memory-mapping-&-streaming.srt

---

subtitles/zh-CN/38_saving-and-reloading-a-dataset.srt

docs(zh-cn): Reviewed 38_saving-and-reloading-a-dataset.srt #390

docs(zh-cn): Reviewed 38_saving-and-reloading-a-dataset.srt

---

subtitles/zh-CN/37_datasets-+-dataframes-=-❤️.srt

docs(zh-cn): Reviewed 37_datasets-+-dataframes-=-❤️.srt #390

docs(zh-cn): Reviewed 37_datasets-+-dataframes-=-❤️.srt

---

subtitles/zh-CN/35_loading-a-custom-dataset.srt

docs(zh-cn): 35_loading-a-custom-dataset.srt #390

docs(zh-cn): Reviewed 35_loading-a-custom-dataset.srt

---

utils/generate_subtitles.py

Reverts huggingface/course#566 (wrong branch to merge!)

Revert "Bump release"

---

chapters/en/chapter1/5.mdx

Fix chapter1/5 old documentation links

---

chapters/es/_toctree.yml
chapters/es/chapter0/1.mdx
chapters/es/chapter1/10.mdx
chapters/es/chapter2/4.mdx
chapters/es/chapter2/6.mdx
chapters/es/chapter3/1.mdx
chapters/es/chapter3/2.mdx
chapters/es/chapter3/3.mdx
chapters/es/chapter3/3_tf.mdx
chapters/es/chapter3/4.mdx
chapters/es/chapter3/5.mdx
chapters/es/chapter3/6.mdx
chapters/es/chapter5/4.mdx
chapters/es/glossary/1.mdx

Hey @lewtun! Here is the translation to Spanish of the remaining files of Chapter 3 (#38): 
- translate 3.3
- translate 3.3_tf
- translate 3.5
- translate 3.6
- update quiz titles for consistency across chapters
- fix some typos found in other files -> cherry-picked the commit into a separate PR https://github.com/huggingface/course/pull/511
Questions about translations:
- logits
- cased/uncased

Translate Chapter 3 to Spanish

---

chapters/es/_toctree.yml
chapters/es/chapter6/1.mdx
chapters/es/chapter6/10.mdx
chapters/es/chapter6/2.mdx
chapters/es/chapter6/3.mdx
chapters/es/chapter6/3b.mdx
chapters/es/chapter6/4.mdx
chapters/es/chapter6/5.mdx
chapters/es/chapter6/6.mdx
chapters/es/chapter6/7.mdx
chapters/es/chapter6/8.mdx
chapters/es/chapter6/9.mdx

Hey @lewtun , I finished the translation of Chapter 6: #38 
Includes translation of all the sections. I would say the only translation issue is around the word *"offsets"* in the context of `FastTokenizers`, I have never used the word before (so I left it as is) so I would appreciate it if other Spanish native speakers jump in if they have any suggestions on the translation of the word.
Thanks in advance.
Alfonso

Translating Chapter 6 to Spanish

---

chapters/zh-CN/chapter3/2.mdx

docs: mdx typo

---

chapters/fr/chapter2/2.mdx

In French, "doesn't make sense" translates in "n'a pas de sens".

Chapter 2.2 - doesn't make sense French translation

---

chapters/fr/chapter2/1.mdx

In this context, the word "hackable" doesn't translate in "piratable" (which conveys the notion of illegal piracy). I believe that "modifiable" (i.e can be modified) is more appropriate.

chapter 2's introduction hackable French translation

---

chapters/zh-CN/_toctree.yml

fix typo: 
A full training 一个完整的训练过程

typo fix: _toctree.yml

---

chapters/en/chapter1/1.mdx

Cleaning up this reference to nonexistent content:

Remove mention of chapters 10-12

---

README.md

cc @nataliaElv @stevhliu for viz if you need to deploy the course content yourselves.

Add instructions for deployment

---

chapters/en/chapter11/1.mdx
chapters/en/chapter11/2.mdx
chapters/en/chapter11/3.mdx
chapters/en/chapter11/4.mdx

* Fixed some broken links
* Updated URL inside <Tip> to be rendered correctly (see image below).
* Minor typos
@burtenshaw

Updated small nits in `Chapter 11`

---

chapters/en/chapter11/4.mdx

Fixed small typo to make it less confusing

fix: typo in lora section (chapter11/4.mdx)

---

chapters/en/chapter1/7.mdx

the title was appearing 2 times on the hugging face website

Update 7.mdx : correct missing brackets in title

---

chapters/en/_toctree.yml
chapters/en/chapter1/10.mdx
chapters/en/chapter1/11.mdx
chapters/en/chapter1/7.mdx
chapters/en/chapter1/8.mdx
chapters/en/chapter1/9.mdx

This PR introduces an embedded quiz to chapter 1 which returns a certificate when completed.
The PR does this:
- move the current ungraded quiz to the middle where it make sense
- add the certified quiz at the end
- updated the TOC

[ENHANCEMENT] add certified quiz to chapter 1

---

chapters/my/chapter0/1.mdx
chapters/my/chapter1/7.mdx

This PR provides refinements to the Myanmar translation for Chapter 0, Section 1 (`1.mdx`).
*   **Updated Terminology:** Key terms and phrases have been re-evaluated and adjusted for improved clarity and consistency, making the content more accessible.
*   **Expanded Glossary:** The per-chapter glossary has been updated with additional technical terms to further aid reader comprehension.
@lewtun, @stevhliu, and @sittyatenyo - please review these updates.
Closes #1042

fix(my): Refine Myanmar translation for Chapter 0, Section 1
