- chapters/en/chapter6/2.mdx
In the examples given, `Ġ` denotes a space while `Ċ` denotes a newline, but the explanatory text says the reverse. This PR fixes this mistake in the text.
> Correct typo mixing up space and newline symbols

- .github/workflows/build_documentation.yml
- .github/workflows/build_pr_documentation.yml
- chapters/ja/_toctree.yml
- chapters/ja/chapter0/1.mdx
This is the first PR about translating to Japanese.
In this PR, I translate chapter0/1.mdx.
> Translate to Japanese Chapter0

- chapters/en/chapter8/7.mdx
In the quiz for chapter 8, question 8 the final option when selected shows as incorrect, although I think is should be correct. 
Marking as correct in the corresponding `.mdx` file
> Mark third option on chapter 8, question 8 as correct

- chapters/en/chapter9/1.mdx
- chapters/en/chapter9/2.mdx
- chapters/en/chapter9/3.mdx
- chapters/en/chapter9/4.mdx
- chapters/en/chapter9/6.mdx
- chapters/en/chapter9/7.mdx
Fix a few typos in Gradio course.
VSCode trimmed all the extra whitespaces it seems, I can remove that if that's an issue.
> Fix typos in Gradio course (chapter 9)

- chapters/en/chapter6/5.mdx
- chapters/en/chapter6/6.mdx
- chapters/en/chapter6/7.mdx
Issues mentioned in https://github.com/huggingface/course/issues/121
cc: @lewtun
> fix typos in bpe, wordpiece, unigram

- chapters/en/chapter7/6.mdx
- chapters/en/chapter7/7.mdx
typos
missing code
code consistency
> Part 7: Training a causal... fixes

- README.md
- chapters/tr/_toctree.yml
- chapters/tr/chapter1/6.mdx
added Turkish contributors part, chapter 1/6 and toctree file.
> [TR] Translated Chapter 1.6 🤗

- chapters/pt/_toctree.yml
- chapters/pt/chapter1/2.mdx
> [PT][Chapter 01 - 2.mdx] - issue #51

- chapters/es/TRANSLATING.txt
- chapters/es/_toctree.yml
- chapters/es/glossary/1.mdx
The goal of this PR:
* Follow up on a suggestion made by @lewtun in a previous [PR](https://github.com/huggingface/course/pull/162)
* Provide both TRANSLATING.TXT and glossary which are adaptations from the German translation.
* Provide basic documentation for the Spanish translations conventions.
* Increase consistency and speed when translating new chapters.
> Add translating notes and glossary to Spanish

- README.md
the old link: [https://discord.gg/fvRrmu27](https://discord.gg/fvRrmu27) is invalid. The new link is the same of the HF site: [https://discord.gg/JfAtkvEtRb](https://discord.gg/JfAtkvEtRb)
> fix invite discord link in readme

- chapters/pt/_toctree.yml
- chapters/pt/chapter5/1.mdx
- chapters/pt/chapter5/2.mdx
> [PT] add 5.1 and 5.2

- requirements.txt
This PR pins version of black to make sure developers can get the right version of black on their dev environment.
Currently, requirements.txt doesn't specify a version of black. As a result, `pip install -r requirements.txt` retains black if it is already installed even if it is older version.
This will help prevent an issue like https://github.com/huggingface/course/issues/114#issuecomment-1154041570 from happening.
> Pin version of black

- chapters/pt/_toctree.yml
- chapters/pt/chapter6/1.mdx
#51 
Pull request for the first section of chapter 6 in the Portuguese language.
> [PT] add chapter 6.1

- chapters/pt/_toctree.yml
- chapters/pt/chapter1/10.mdx
- chapters/pt/chapter1/4.mdx
- chapters/pt/chapter1/5.mdx
- chapters/pt/chapter1/6.mdx
- chapters/pt/chapter1/7.mdx
- chapters/pt/chapter1/8.mdx
- chapters/pt/chapter1/9.mdx
> Chapter 01 - Done [PT] #51

- chapters/en/chapter7/3.mdx
- chapters/fr/chapter7/3.mdx
- chapters/ja/chapter7/3.mdx
The original import doesn't work. Not sure if the fix should be updating the import of exporting the `tf_default_data_collator` as per this PR or to export it in `__init__.py`
> tf_default_data_collator import

- chapters/en/chapter7/4.mdx
- chapters/en/chapter7/5.mdx
With the release of `transformers` v4.22.0, the `as_target_tokenizer` context managers have been deprecated. This PR refactors the translation and summarisation chapters to accommodate the new API
> Refactor tokenization of targets for transformers v4.22

- chapters/en/chapter6/3b.mdx
- chapters/fr/chapter6/3b.mdx
- chapters/th/chapter6/3b.mdx
- chapters/vi/chapter6/3b.mdx
- chapters/zh-CN/chapter6/3b.mdx
For consistency with earlier logic in this section, we take the second dimension of the `scores` tensor to compute the start and end indices. It has no effect on the outputs since `scores` is square, but helps avoid confusion.
Closes #282
> Fix question answering indices

- chapters/en/chapter5/5.mdx
- chapters/en/chapter5/6.mdx
Thanks to a bug report from a community member, I took the opportunity to refactor the dataset upload to use the much simpler `push_to_hub()` method instead of the clunky repo creation.
cc @albertvillanova @lhoestq 
Fixes https://github.com/huggingface/datasets/issues/5086
> Refactor dataset upload in Chapter 5 / section 5

- chapters/de/chapter3/6.mdx
Noticed two `undefined` in the new render, because the `text` key was capitalized.
Relates to #43
> [de] Fix keywords in quiz chapter 3

- chapters/en/chapter2/2.mdx
Replace "inputs" with "outputs".
> Typo in Chapter 2, Section 2

- .github/workflows/quality.yml
3.6 is no longer supported.
Run actions/setup-python@v2
with:
python-version: 3.6
token: ***
Version 3.6 was not found in the local cache
Error: Version 3.6 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
> Upgrade python version in the workflow

- .github/workflows/quality.yml
- subtitles/README.md
- utils/convert_bilingual_monolingual.py
This script is used for removing english caption from bilingual caption files to make it monolingual.
The english caption line is conventionally placed at the last line of each caption block in srt files. So the newly created script is aimed at removing the last line of each caption block of committed bilingual caption. 
This script is developed and tested in *python v3.11*.
> python3 convert_bilingual_monolingual.py -i \<input_file\> -o \<output_file\>
**Example**
* For instance, the input file name is "test.cn.en.srt", and you name your output file as "output_test.cn.srt" *
> python3 convert_bilingual_monolingual.py -i test.cn.en.srt -o output_test.cn.srt
> created new script for converting bilingual captions to monolingual caption

- .github/workflows/quality.yml
- subtitles/zh-CN/56_data-processing-for-masked-language-modeling.srt
docs(zh-cn): Reviewed 56_data-processing-for-masked-language-modeling.srt #390
> docs(zh-cn): Reviewed 56_data-processing-for-masked-language-modeling.srt

- subtitles/zh-CN/58_what-is-domain-adaptation.srt
docs(zh-cn): Reviewed 58_what-is-domain-adaptation.srt #390
> docs(zh-cn): Reviewed 58_what-is-domain-adaptation.srt

- subtitles/zh-CN/63_data-processing-for-causal-language-modeling.srt
docs(zh-cn): Reviewed 63_data-processing-for-causal-language-modeling.srt #390
> docs(zh-cn): Reviewed 63_data-processing-for-causal-language-modeling.srt

- subtitles/zh-CN/64_using-a-custom-loss-function.srt
docs(zh-cn): Reviewed 64_using-a-custom-loss-function.srt #390
> docs(zh-cn): Reviewed 64_using-a-custom-loss-function.srt

- chapters/en/chapter7/3.mdx
- chapters/fr/chapter7/3.mdx
- chapters/ja/chapter7/3.mdx
- chapters/vi/chapter7/3.mdx
- chapters/zh-CN/chapter7/3.mdx
- utils/generate_notebooks.py
Fixes an issue reported by @xianbaoqian where the pushed models on the Hub were missing the tokenizer files. The fix is to include the tokenizer in the `Trainer` before training / pushing to the Hub
> Add tokenizer to MLM Trainer

- chapters/de/chapter1/6.mdx
- chapters/en/chapter1/6.mdx
- chapters/es/chapter1/6.mdx
- chapters/fr/chapter1/6.mdx
- chapters/hi/chapter1/6.mdx
- chapters/it/chapter1/6.mdx
- chapters/ja/chapter1/6.mdx
- chapters/ko/chapter1/6.mdx
- chapters/pt/chapter1/6.mdx
- chapters/ru/chapter1/6.mdx
- chapters/th/chapter1/6.mdx
- chapters/tr/chapter1/6.mdx
- chapters/vi/chapter1/6.mdx
- chapters/zh-CN/chapter1/6.mdx
GPT link to the model docs is dead. Added new correct link.
> Fix dead GPT model docs link.

- chapters/zh-CN/chapter8/3.mdx
Some unnatural translations have been revised to use expressions more popular with Chinese readers
> Revise some unnatural translations

- subtitles/zh-CN/08_what-happens-inside-the-pipeline-function-(pytorch).srt
> docs(zh-cn): Reviewed No. 08 - What happens inside the pipeline function? (PyTorch)

- subtitles/zh-CN/10_instantiate-a-transformers-model-(pytorch).srt
> docs(zh-cn): Reviewed No. 10 - Instantiate a Transformers model (PyTorch)

- chapters/ru/TRANSLATING.txt
- chapters/ru/_toctree.yml
- chapters/ru/glossary/1.mdx
The first version of the glossary and the translation guide for Russian. It has been mostly adapted from the German one since most of the guidelines apply to Russian as well.
Any discussion about the choice of terms in the glossary is very welcome here. Once everyone is happy, we can merge it into the main branch.
Issue #75 
@pdumin @blademoon
> [ru] Added the glossary and translation guide

- subtitles/en/41_text-embeddings-&-semantic-search.srt
Some texts are used as function name and variable name, so changed the related texts in subtitle and use the same as it  appeared in video.
> optimized english subtitle of 41_text-embeddings-&-semantic-search.srt

- chapters/vi/chapter7/7.mdx
There was an unnecessary `</Tip>`
> Fix syntax in vi/chapter7/7.mdx

- chapters/en/chapter1/10.mdx
Changed 'perspires' to 'persists' in Chapter 1 quiz
Fixes #585 
I'm new to open source - please let me know if anything needs to be changed or if my process is wrong. Figured I'd start with something simple. Thanks all!
> changed 'perspires' to 'persists' in chapter 1 quiz

- chapters/en/chapter7/3.mdx
The link `/course/en/chapter7/section6` does not exist in the course.  Corrected to `/course/en/chapter7/6`.
> The GPT2 course link is broken

- chapters/en/chapter1/4.mdx
In context to "training with a dataset specific to your task" and "train directly for the final task", I was not able to infer easily that "directly" here implies training from scratch.
> refactor: rephrase text to improve clarity and specificity

- chapters/en/chapter7/4.mdx
- chapters/fr/chapter7/4.mdx
Removed judgmental arguments that shouln't be here in the first place.
> Removed judgmental arguments

- chapters/en/chapter7/6.mdx
`get_lr()` is called as part of this function, but the function is not declared anywhere in the script. This change removes this portion of the code since it is non-necessary.
> Remove `get_lr()` from logs which refers to nonexistent function

- chapters/en/chapter6/7.mdx
Duplicated `the` was removed:
> Now your turn! Write the code to compute the ~the~ frequencies above and double-check that the results shown are correct, as well as the total sum.
> Typo in `Now your turn!` section in the `Unigram tokenization` section

- chapters/en/chapter7/3.mdx
`chunk_size` should be instead of `block_size` (`block_size` was never mentioned before)
> `chunk_size` should be instead of `block_size`

- chapters/ko/chapter1/9.mdx
- chapters/ko/chapter2/2.mdx
> fix korean typo,

- chapters/en/chapter7/6.mdx
The variable `tokenized_dataset` isn't initialized in the code. Leading to exception when the cell is reached. On the other hand `tokenized_datasets` var does exist. It was probably intended to be used in the first place. 
Closes: #702
> Changing `tokenized_dataset` to `tokenized_datasets`

- utils/generate_notebooks.py
Hello, when I followed notebook ["Fine-tuning a model with the Trainer API or Keras"](https://huggingface.co/learn/nlp-course/en/chapter3/3?fw=pt) I encountered this issue:
Hope this PR will fix that in the docs
> [doc-fix] Add accelerate required for notebook 3/3

- chapters/fr/chapter3/1.mdx
Hello,
Thanks a lot for this great course. I propose to fix a small typo in the French course (`chapter3/1.mdx`)
Thank you.
Laurent
> fix: typo in French course (chapter3/1.mdx)

- chapters/en/chapter9/3.mdx
Replace the deprecated methods by those in Gradio 5.13.2:
1. `gr.Textbox(type="number")` --> `gr.Number()`.
2. `gr.Audio` covers both microphone and file upload without specifying `source`.
Error about `gr.Textbox(type="number"):
```
Device set to use cuda:0
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 21
14     transcription = model(audio)["text"]
15     return transcription
18 gr.Interface(
19     fn=transcribe_audio,
20     inputs=[
---> 21         gr.Audio(source="microphone", type="filepath", optional=True),
22         gr.Audio(source="upload", type="filepath", optional=True),
23     ],
24     outputs="text",
25 ).launch()
File …
```
> Replace Gradio deprecated methods in 3.mdx

- chapters/en/chapter11/3.mdx
- `evaluation_startegy` -> `eval_strategy`: remove depreciation warning
- adding `"all"` to the dataset loader to avoid raising error
> chore(chap11): fixing few typos

- chapters/en/_toctree.yml
- chapters/en/chapter12/1.mdx
- chapters/en/chapter12/2.mdx
- chapters/en/chapter12/3.mdx
- chapters/en/chapter12/4.mdx
- chapters/en/chapter12/5.mdx
- chapters/en/chapter12/6.mdx
* add basic introduction for students
* page on the basics of RL
* add page on grpo and the deep seek paper
* add grpo in trl page
* add coming soon page
* add ungraded quizzes on rl and r1
* update toc
* format code snippets
* fix images in rl page
* fix and make correct grpo section in rl page (2.mx)
* fix preference data mistake
* fix use of 'preference data' in grpo paper walkthrough
* improve dpo and ppo comparison in RL page (2.mdx)
* respond to feedback on TRL page
* add pseudo code and limitations to the GRPO paper page
* expand grpo comparison in RL page
* add examples of dummy reward functions to TRL page
* add length function examples to TRL page
* format code snippets
* Fix all GRPO acronyms
* remove mention of preference datasets
* Apply suggestions from code review …
> Bump_release_chapter12

- chapters/en/_toctree.yml
- chapters/en/chapter1/1.mdx
- chapters/en/chapter1/2.mdx
- chapters/en/chapter7/1.mdx
- chapters/en/chapter7/8.mdx
This PR renames the course but it does not remove NLP. It is a minimal effort to integrate the course more with the current community. It does this in two ways:
- introduces llms and their difference to other nlp models
- uses the concept of 'classical nlp' to refer to model's like classifiers.
> [RENAME] rename nlp course to LLM course

- chapters/en/chapter12/5.mdx
This pull request includes a small typo correction in the `chapters/en/chapter12/5.mdx` file. The change fixes a typo in the URL link for the `SmolLM2-135M` model.
* [`chapters/en/chapter12/5.mdx`](diffhunk://#diff-b2b8fe41af7e5083b450f9d4f5da8941c6da5b9f76d933fbda18df56b2eea69eL61-R61): Corrected the URL link for the `SmolLM2-135M` model by removing an extra 'h' character.
> fix typo in SmolLM2-135M model link

- chapters/en/chapter5/3.mdx
- chapters/es/chapter5/3.mdx
- chapters/fr/chapter5/3.mdx
- chapters/it/chapter5/3.mdx
- chapters/pt/chapter5/3.mdx
- chapters/ru/chapter5/3.mdx
- chapters/vi/chapter5/3.mdx
- chapters/zh-CN/chapter5/3.mdx
- chapters/zh-TW/chapter5/3.mdx
In [chapter 5 section 3](https://huggingface.co/learn/llm-course/chapter5/3#from-datasets-to-dataframes-and-back), the code for computing the class distribution with Pandas dataframe method chaining does not work as expected due to the incorrect key in column mapping for the `rename` method. 
This PR fixes the issue by changing the key `condition` to `count` in all available languages.
> Fix code error in chapter 5 section 3

- chapters/en/chapter7/2.mdx
Switch to processing_class; tokenizer parameter deprecated in Trainer constructor
> Mistake with Trainer constructor - Chapter 7

- chapters/en/chapter11/3.mdx
While these are defined in the previous section 11.2, for someone copying the code to run onto their notebooks, this would fail.
> Defining model and tokenizer before using them

- chapters/en/chapter6/4.mdx
Small typo in docs where the link to the Unigram algorithm from discussion on pre-tokenization (SentencePiece specifically).
~~Fixes #1736~~
> EDIT: Realized I might've opened the issue in the wrong repo 😅. Here's the link to that issue for reference: https://github.com/huggingface/hub-docs/issues/1736
> I won't open a new issue to reduce confusion.
> Fix typo: Unigram section link

- chapters/en/_toctree.yml
- chapters/en/chapter2/1.mdx
- chapters/en/chapter2/2.mdx
- chapters/en/chapter2/3.mdx
- chapters/en/chapter2/4.mdx
- chapters/en/chapter2/5.mdx
- chapters/en/chapter2/6.mdx
- chapters/en/chapter2/8.mdx
- chapters/en/chapter2/9.mdx
This is a minor improvement to chapter 2 to do these things:
- remove tensorflow examples and videos
- add a page on TGI, vLLM, and llama.cpp
> Improve and re-release chapter 2

- chapters/en/chapter1/9.mdx
Added "to" in the sentence to make it more cohesive.
> added "to" in a sentence.mdx

- chapters/en/chapter1/4.mdx
There was a slight jumbling of sentences. I reordered it in order for it make sense.
> fix typo in (en) chapter 1, sub-chatper 4

- chapters/en/chapter1/5.mdx
Added the missing link for the `generation_strategies` guide.
> Update 5.mdx: Added generation_strategies guide missing link

- chapters/my/_toctree.yml
- chapters/my/chapter7/1.mdx
- chapters/my/chapter7/2.mdx
- chapters/my/chapter7/3.mdx
- chapters/my/chapter7/4.mdx
- chapters/my/chapter7/5.mdx
- chapters/my/chapter7/6.mdx
- chapters/my/chapter7/7.mdx
- chapters/my/chapter7/8.mdx
- chapters/my/chapter7/9.mdx
This PR adds the Myanmar translation for ``Chapter 7: Classical NLP Tasks``.
The translation includes per-chapter glossaries for technical terms, aiming for clarity and accessibility. Specialized English terms are retained in the main text to align with technical standards, with their explanations provided in the glossaries.
@lewtun, @stevhliu, and @sittyatenyo - please review this translation.
Closes #1042
> feat(my): Add Myanmar translation for Chapter 7 and per-chapter Glossary
